# Generated by Django 4.1.1 on 2022-09-14 13:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import func_basic.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Metadata',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('catalog_ref', models.CharField(max_length=150)),
                ('rights_info', models.CharField(max_length=150)),
                ('item_meta_itemclass', models.CharField(max_length=150)),
                ('item_meta_versioncreated', models.CharField(max_length=150)),
                ('item_meta_publicationstatus', models.CharField(max_length=150)),
                ('item_meta_provider', models.CharField(max_length=150)),
                ('content_meta_creator', models.CharField(max_length=150)),
                ('content_meta_located', models.CharField(max_length=150)),
                ('content_meta_subject', models.CharField(max_length=150)),
                ('content_meta_headline', models.CharField(max_length=150)),
                ('part_meta', models.CharField(max_length=150)),
                ('inline_ref', models.CharField(max_length=150)),
                ('derived_from', models.CharField(max_length=150)),
                ('hop_history', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sutien', models.CharField(max_length=150)),
                ('authors', models.CharField(max_length=150)),
                ('editors', models.CharField(max_length=150)),
                ('news_text', models.CharField(max_length=15000)),
                ('keywords', models.CharField(max_length=1500)),
                ('related_news', models.CharField(max_length=1500)),
                ('related_publisher', models.CharField(max_length=350)),
                ('posted_on', models.CharField(max_length=150)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='func_basic.basic_metadata')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=350)),
                ('photographer', models.CharField(max_length=350)),
                ('keywords', models.CharField(max_length=350)),
                ('used_equipament', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('image', models.FileField(blank=True, null=True, upload_to=func_basic.models.upload_path)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='func_basic.basic_metadata')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem_Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('data', models.CharField(max_length=350)),
                ('type_graphic', models.CharField(max_length=350)),
                ('designer', models.CharField(max_length=350)),
                ('graphic_image', models.FileField(blank=True, null=True, upload_to=func_basic.models.upload_path)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='func_basic.basic_metadata')),
            ],
        ),
    ]
