# Generated by Django 4.1.1 on 2022-09-14 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('func_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
