# Generated by Django 4.0.6 on 2022-08-18 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('func_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Metadata',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('catalog_ref', models.CharField(max_length=150)),
                ('rights_info', models.CharField(max_length=150)),
                ('item_meta_itemclass', models.CharField(max_length=150)),
                ('item_meta_versioncreated', models.CharField(max_length=150)),
                ('item_meta_publicationstatus', models.CharField(max_length=150)),
                ('item_meta_provider', models.CharField(max_length=150)),
                ('content_meta_creator', models.CharField(max_length=150)),
                ('content_meta_located', models.CharField(max_length=150)),
                ('content_meta_subject', models.CharField(max_length=150)),
                ('content_meta_headline', models.CharField(max_length=150)),
                ('part_meta', models.CharField(max_length=150)),
                ('inline_ref', models.CharField(max_length=150)),
                ('derived_from', models.CharField(max_length=150)),
                ('hop_history', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='user_login',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='NewsItem_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sutien', models.CharField(max_length=150)),
                ('authors', models.CharField(max_length=150)),
                ('editors', models.CharField(max_length=150)),
                ('news_text', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=150)),
                ('related_news', models.CharField(max_length=150)),
                ('related_publisher', models.CharField(max_length=150)),
                ('posted_on', models.CharField(max_length=150)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='func_basic.basic_metadata')),
            ],
        ),
    ]
