# Generated by Django 4.0.6 on 2022-08-18 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import func_basic.models


class Migration(migrations.Migration):

    dependencies = [
        ('func_basic', '0002_basic_metadata_alter_user_login_id_newsitem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_metadata',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='newsitem_text',
            name='keywords',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='newsitem_text',
            name='news_text',
            field=models.CharField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='newsitem_text',
            name='related_news',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='newsitem_text',
            name='related_publisher',
            field=models.CharField(max_length=350),
        ),
        migrations.CreateModel(
            name='NewsItem_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=350)),
                ('photographer', models.CharField(max_length=350)),
                ('keywords', models.CharField(max_length=350)),
                ('used_equipament', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('image', models.FileField(blank=True, null=True, upload_to=func_basic.models.upload_path)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='func_basic.basic_metadata')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem_Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('data', models.CharField(max_length=350)),
                ('type_graphic', models.CharField(max_length=350)),
                ('designer', models.CharField(max_length=350)),
                ('graphic_image', models.FileField(blank=True, null=True, upload_to=func_basic.models.upload_path)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='func_basic.basic_metadata')),
            ],
        ),
    ]
